# /ansible-project/roles/s3_upload/tasks/main.yml
- name: Install boto and boto3
  pip:
    name:
      - boto
      - boto3
    state: present
  become: true


- name: Upload index.html to S3
  amazon.aws.aws_s3:
    bucket: vegas-todo-bucket
    object: index.html
    src: "{{ project_path }}/index.html"
    mode: put
    permission: public-read